name: CI
on:
  - pull_request
  - push

jobs:
  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils zip

      - uses: actions/checkout@v3

      - name: Build image for x86_64 with BIOS mode and without GPT
        run: |
          sudo ./alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 6G \
              --repositories-file example/repositories \
              --packages "$(cat example/packages)" \
              --fs-skel-dir example/rootfs \
              --fs-skel-chown root:root \
              --script-chroot \
              alpine-bios.qcow2 -- ./example/configure.sh
          qemu-img convert -f qcow2 alpine-bios.qcow2 -O vdi alpine-bios.vdi
          pwd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: /home/runner/work/pythonos/pythonos/alpine-bios.vdi

      - run: |
          # zip -v -j alpine-pythonui.zip /home/runner/work/pythonos/pythonos/alpine-bios.vdi
          zip -v -j alpine-pythonui.zip alpine-bios.vdi

      # - name: Release
      #   uses: technote-space/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: alpine-pythonui.zip
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: alpine-pythonui.zip
